### PR TITLE
allow to pass time as number or date as well

### PR DESCRIPTION
**Pull request by sodik82**
I opt for flexibility, as passing only string as time does not guarantee that it is valid time.

### CODE REVIEW

**Comment by TylerLH** [comment]
Would you care to elaborate on this further?

**Comment by sodik82** [comment]
`moment.js` library allow input in different formats - not only string, but also date and number as well. therefore I suggest to remove "hard string" constraint from proptypes in order to allow more flexible usage of your component.

**Comment by TylerLH** [comment]
In that case, rather than using `React.PropTypes.any`, I would argue that we should be a bit more explicit, such as:

``` js
React.PropTypes.oneOfType([
    React.PropTypes.string,
    React.PropTypes.number,
    React.PropTypes.array,
    React.PropTypes.instanceOf(Date)
])
```

It may also be worth considering allowing the user to pass their own Moment instance that could be used instead of constructing a new one. Thoughts?

**Comment by sodik82** [comment]
sure, works for me. 

> pass their own Moment instance

could be useful in some situations - if we want to make it even more flexible, we can pass in the function that will format the time. however question is if go that far :)

**Comment by TylerLH** [comment]
Definitely worth exploring later on. In the meantime, this is a great step forward. Thanks!

**Pull request merged**
